	NDefines.NDiplomacy.FORM_NON_AGGRESSION_PACT_INTERACTION_ENABLED = 0
	NDefines.NDiplomacy.FORM_ALLIANCE_INTERACTION_ENABLED = 0
	NDefines.NDiplomacy.INVITE_TO_COURT_INTERACTION_ENABLED = 0
	NDefines.NDiplomacy.BUY_FAVOR_INTERACTION_ENABLED = 0